### ISSUE TITLE
Custom HttpClient failing

### ISSUE THREAD

**Issue by willladislaw** [goto-bus-stop/dart-event-source#10]
Attached listener to EventSource `object. Getting no data. 

Also, have to call `request.close()` to hit the endpoint (url) else fails to connect (not sure if this is the correct thing to do).
```
    final client = new HttpClient();
        String url = 'http://localhost:8080/api/conn/mobile-$username';
    
        final request = await client.getUrl(Uri.parse(url));
        request.headers.contentType = new ContentType("application", "json", charset: "utf-8");
        request.headers.set(HttpHeaders.authorizationHeader,  "Bearer ${currentOauthAccount.token}");

       request.close();

        final events = EventSource(Uri.parse(url), clientFactory:() => client);
    
        final subscription = events.events.listen((MessageEvent message) {
          print('${message.name}: ${message.data}');
        });
        Timer(Duration(seconds: 60), () {
          // Canceling the subscription closes the connection.
          subscription.cancel();
        });


```

**Comment by goto-bus-stop** [comment]
EventSource internally handles creating a request, sending and closing it. I think you're trying to send an Authorization header along with the request to the event source endpoint?
At the moment, this package does not provide a way to customise the requests it sends. This is also not supported by the `EventSource` API on the web. If your server requires an Authorization header, it is impossible to use your event source endpoint from the web.

The one thing you could do with _this_ package is create a subclass of HttpClient and override its `getUrl` method, then set the Authorization header there.

On the web, there are two ways to authenticate EventSource requests:
- by putting a token into the URL (with https)
- by putting a token in a cookie
Cookies are not currently supported by this package but it would be nice to add that in the future.

**Comment by willladislaw** [comment]
Thanks
